// Source: https://co.wikipedia.org/wiki/ISO_3166-2
export const galicianCountryNames: Record<string, string> = {
  ANC: "Ancares",
  ARC: "Arçua",
  ARN: "Arnoia",
  BAL: "Baixa Límia",
  BAM: "Baixo Minho",
  BAR: "Barbança",
  BER: "Bergantinhos",
  BEZ: "Berzo",
  BUR: "Burom",
  CAB: "Cabreira",
  CAL: "Caldas",
  CAR: "Carvalhinho",
  CEL: "Celanova",
  CHA: "Chantada",
  COM: "Compostela",
  CND: "Condado",
  COR: "Corunha",
  COS: "Costa da Morte",
  COU: "Courel",
  DEC: "Deça",
  EUM: "Eume",
  LIM: "Límia",
  LUG: "Lugo",
  MAR: "Marinha",
  MAS: "Marinhas",
  MON: "Monte Rei",
  MOR: "Morraço",
  MUR: "Muros-Noia",
  ORD: "Ordes",
  ORT: "Ortegal",
  OUR: "Ourense",
  PAR: "Paradanta",
  PON: "Ponte Vedra",
  RIB: "Ribeiro",
  SAL: "Salnês",
  SAR: "Sárria",
  SEA: "Seabra",
  TAV: "Taveirós",
  TCH: "Terra Chá",
  TCA: "Terra de Caldelas",
  TLE: "Terra de Lemos",
  TME: "Terra de Melide",
  TMO: "Terra de Montes",
  TNA: "Terra de Návia-eu",
  TTR: "Terra de Trives",
  ULH: "Ulhoa",
  VDO: "Valdeorras",
  VDI: "Vale do Íbias",
  VIA: "Viana",
  VIG: "Vigo",
  TRA: "Trasancos",
};
